global using System;
global using Modding.Menu;
global using Modding.Menu.Config;
global using UnityEngine;
global using UnityEngine.UI;
global using Satchel.BetterMenus;
global using Random = UnityEngine.Random;
global using Object = UnityEngine.Object;
global using MethodAction = Core.FsmUtil.Actions.MethodAction;
global using System.Collections;
global using System.Collections.Generic;
global using System.Linq;
global using HutongGames.PlayMaker;
global using Core.FsmUtil;
//global using Satchel;
global using HKMirror;
global using HKMirror.Reflection;
global using HKMirror.Reflection.InstanceClasses;
global using HKMirror.Reflection.SingletonClasses;
global using HKMirror.Hooks.OnHooks;
global using HKMirror.Hooks.ILHooks;
global using HallownestVocalizedAudioLoader;
global using UnityEngine.SceneManagement;
global using Modding;
global using USceneManager = UnityEngine.SceneManagement.SceneManager;
global using HutongGames.PlayMaker.Actions;
global using System.IO;
global using System.Reflection;

